spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/auction_service
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
